import Head from "next/head";

export default function Home({ users }) {
  console.log("users: ", users);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Cheems Store</h1>
      {users.map((user) => (
        <h2 key={user.email}>{user.email}</h2>
      ))}
    </div>
  );
}

export const getStaticProps = async () => {
  const answer = await fetch(
    `https://jsonplaceholder.typicode.com/users?_limit=8`
  );
  const users = await answer.json();

  return {
    props: {
      users,
    },
  };
};
